export const products = [
  { id: 1, name: "Redmi Note 13", category: "Phone", price: 199, description: "6.67 inch AMOLED, 108MP camera, 5000mAh battery" },
  { id: 2, name: "Samsung Galaxy A35", category: "Phone", price: 349, description: "Super AMOLED display, 50MP camera, IP67 water resistance" },
  { id: 3, name: "Google Pixel 8a", category: "Phone", price: 499, description: "Great camera, clean Android, 7 years of updates" },
  { id: 4, name: "iPhone 15", category: "Phone", price: 799, description: "A16 chip, 48MP camera, USB-C" },
  { id: 5, name: "Samsung Galaxy S24 Ultra", category: "Phone", price: 1199, description: "Flagship, 200MP camera, S Pen, titanium frame" },
  { id: 6, name: "HP Pavilion 15", category: "Laptop", price: 649, description: "Ryzen 5, 16GB RAM, 512GB SSD, everyday use" },
  { id: 7, name: "MacBook Air M2", category: "Laptop", price: 999, description: "Fanless, 18-hour battery, great for students and creators" },
  { id: 8, name: "ASUS ROG Strix G16", category: "Laptop", price: 1399, description: "RTX 4060 gaming laptop, 165Hz display" },
  { id: 9, name: "Sony WH-1000XM5", category: "Headphones", price: 349, description: "Industry-leading noise cancelling, 30-hour battery" },
  { id: 10, name: "boAt Rockerz 450", category: "Headphones", price: 25, description: "Budget wireless headphones, 15-hour battery" },
  { id: 11, name: "Apple Watch SE", category: "Smartwatch", price: 249, description: "Fitness tracking, heart rate, crash detection" },
  { id: 12, name: "Amazfit Bip 5", category: "Smartwatch", price: 89, description: "Large display, GPS, 10-day battery, budget fitness watch" },
  { id: 15, name: "Nothing Phone (2)", category: "Phone", price: 599, description: "Glyph interface, Snapdragon 8+ Gen 1, 50MP dual camera, 120Hz OLED display" },
  { id: 16, name: "Nothing Phone (3a)", category: "Phone", price: 379, description: "Glyph lights, 50MP triple camera with telephoto, 5000mAh battery, clean software" },
    { id: 17, name: "MacBook Air M3", category: "Laptop", price: 1099, description: "M3 chip, 13 inch Retina display, 18-hour battery, light and fanless" },
  { id: 18, name: "MacBook Pro 14 M3", category: "Laptop", price: 1599, description: "M3 Pro chip, 14 inch Liquid Retina XDR display, 18GB RAM, for editing and heavy work" },
    { id: 14, name: "Nothing Phone (2a)", category: "Phone", price: 349, description: "Glyph LED lights on back, 50MP dual camera, clean software, 5000mAh battery" },
];
